# Generated by Django 2.1.2 on 2018-10-22 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 15, 55, 14, 752085)),
        ),
    ]
