# Generated by Django 2.1.2 on 2018-11-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('alt', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LieuDeVie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alt', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MethodePaiement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alt', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('alt', models.CharField(max_length=30)),
                ('prixAchat', models.IntegerField()),
                ('prixVente', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('idCategorieProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.CategorieProduit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateVente', models.DateTimeField()),
                ('alt', models.CharField(max_length=30)),
                ('selledBy', models.CharField(max_length=30)),
                ('idLieuDeVie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventes.LieuDeVie')),
                ('idMethodePaiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventes.MethodePaiement')),
                ('idProduit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventes.Produit')),
            ],
        ),
    ]
