# Generated by Django 2.1.2 on 2018-11-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='purchaseBy',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
