# Generated by Django 2.1.2 on 2018-11-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_auto_20181114_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prixAchat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prixVente',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vente',
            name='amount',
            field=models.FloatField(),
        ),
    ]
