# Generated by Django 2.1.2 on 2018-11-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_auto_20181114_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='disponible',
        ),
    ]
