# Generated by Django 2.1.2 on 2018-11-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_remove_produit_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='idCategorieProduit',
        ),
    ]
