# Generated by Django 2.1.2 on 2018-11-14 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_auto_20181114_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='idProduit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.Produit'),
        ),
    ]
