# Generated by Django 2.1.2 on 2018-11-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0008_auto_20181114_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='alt',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vente',
            name='purchaseBy',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vente',
            name='selledBy',
            field=models.CharField(max_length=300),
        ),
    ]
