# Generated by Django 2.1.2 on 2018-12-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0009_auto_20181114_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
