# Generated by Django 2.1.2 on 2018-12-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduitTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('alt', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LieuDeVieTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alt', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=300)),
                ('alt', models.CharField(max_length=300)),
                ('prixAchat', models.FloatField()),
                ('prixVente', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VenteTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateVente', models.DateTimeField()),
                ('alt', models.CharField(max_length=30)),
                ('selledBy', models.CharField(max_length=300)),
                ('purchaseBy', models.CharField(max_length=300)),
                ('amount', models.FloatField()),
                ('idLieuDeVie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes_temp.LieuDeVieTemp')),
                ('idProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes_temp.ProduitTemp')),
            ],
        ),
    ]
