# Generated by Django 2.1.2 on 2018-12-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes_temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventetemp',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
