# Generated by Django 2.1.2 on 2018-10-22 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('mdp', models.CharField(max_length=30)),
                ('dateCreation', models.DateTimeField(default=datetime.datetime(2018, 10, 22, 15, 54, 31, 987450))),
                ('dateDerniereConnexion', models.DateTimeField()),
            ],
        ),
    ]
