# Generated by Django 2.1.2 on 2018-10-27 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0002_auto_20181022_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='niveauAuth',
            field=models.CharField(default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 0, 3, 18, 246033)),
        ),
    ]
