# Generated by Django 2.1.2 on 2018-10-27 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0003_auto_20181028_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grainsel',
            field=models.CharField(default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 0, 12, 10, 41278)),
        ),
    ]
