# Generated by Django 2.1.2 on 2018-10-31 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0004_auto_20181028_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 14, 13, 23, 109124)),
        ),
        migrations.AlterField(
            model_name='user',
            name='grainsel',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='mdp',
            field=models.CharField(max_length=100),
        ),
    ]
