# Generated by Django 2.1.2 on 2018-11-03 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0005_auto_20181031_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 18, 13, 1, 824678)),
        ),
    ]
