# Generated by Django 2.1.2 on 2018-11-11 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0009_auto_20181111_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 16, 17, 0, 523497)),
        ),
    ]
