# Generated by Django 2.1.2 on 2018-11-11 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0010_auto_20181111_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 17, 13, 15, 105731)),
        ),
    ]
