# Generated by Django 2.1.2 on 2018-11-12 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0012_auto_20181111_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 9, 32, 20, 441270)),
        ),
    ]
