# Generated by Django 2.1.2 on 2018-11-14 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0014_auto_20181114_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 14, 34, 33, 15942)),
        ),
    ]
