# Generated by Django 2.1.2 on 2018-11-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0016_auto_20181114_1841'),
        ('authBDF', '0016_auto_20181114_2119'),
    ]

    operations = [
    ]
