# Generated by Django 2.1.2 on 2018-11-14 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0020_auto_20181114_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 22, 5, 34, 507497)),
        ),
    ]
