# Generated by Django 2.1.2 on 2018-11-20 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0024_auto_20181114_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 17, 29, 51, 124144)),
        ),
    ]
