# Generated by Django 2.1.2 on 2018-11-20 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0025_auto_20181120_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 17, 42, 12, 113931)),
        ),
    ]
