# Generated by Django 2.1.2 on 2018-11-23 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0026_auto_20181120_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 16, 20, 12, 150873)),
        ),
    ]
