# Generated by Django 2.1.2 on 2018-11-29 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0027_auto_20181123_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 29, 10, 18, 37, 694284)),
        ),
    ]
