# Generated by Django 2.1.2 on 2018-12-02 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0028_auto_20181129_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 12, 17, 37, 514878)),
        ),
    ]
