# Generated by Django 2.1.2 on 2018-12-02 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0029_auto_20181202_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 15, 22, 14, 988481)),
        ),
    ]
