# Generated by Django 2.1.2 on 2018-12-03 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0030_auto_20181202_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 15, 40, 48, 844787)),
        ),
    ]
