# Generated by Django 2.1.2 on 2018-12-03 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0031_auto_20181203_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 16, 22, 10, 886263)),
        ),
    ]
