# Generated by Django 2.1.2 on 2018-12-03 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0032_auto_20181203_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 17, 34, 30, 793306)),
        ),
    ]
