# Generated by Django 2.1.2 on 2018-12-09 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0035_auto_20181205_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 15, 24, 33, 863959)),
        ),
    ]
