# Generated by Django 2.1.2 on 2018-12-09 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0036_auto_20181209_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 16, 17, 30, 884140)),
        ),
    ]
