# Generated by Django 2.1.2 on 2018-12-09 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0037_auto_20181209_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 22, 23, 49, 943299)),
        ),
    ]
