# Generated by Django 2.1.2 on 2019-01-03 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0039_auto_20181210_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 15, 41, 25, 563079)),
        ),
    ]
