# Generated by Django 2.1.2 on 2019-01-03 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0045_auto_20190103_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 19, 13, 16, 707252)),
        ),
    ]
