# Generated by Django 2.1.2 on 2019-01-04 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0049_auto_20190103_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 13, 43, 877448)),
        ),
    ]
