# Generated by Django 2.1.2 on 2018-11-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('alt', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('alt', models.CharField(max_length=30)),
                ('prixAchat', models.IntegerField()),
                ('prixVente', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('idCategorieProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.CategorieProduit')),
            ],
        ),
    ]
