# Generated by Django 2.1.2 on 2018-11-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_produit_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieproduit',
            name='colorGraph',
            field=models.CharField(default='#ffffff', max_length=30),
        ),
    ]
